- name: Create Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: westeurope
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: myResourceGroup
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Public IP of VM
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: myResourceGroup
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: myResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5P8wrRBisCQjVt6KZT9QvqUN5hmtPkEN8gwcJbsIBcJh1Hp3WWDRmCyhE8QAabFTVQVL1RqTXlSN6LytcGg84F2wpeN+yLr6OPyWnmeoj7vYYua8I4VQNT6EendXmrQ9FjccJ7i2mFvzqloYUwyPo0ePuo3XD0dx04twvLo2N7ts/o1LXNlOSU6x/Ai4dXh6U5Lh3F7f6h/z31ICs5zPw0k5jvCO226ha/eATbox2FdTwKtzLfAHRG5IWzqv0mDPoSv5O6AF7cTSRI/sWIuRiGGCg47LRuhM2Brdqn5/WhpqJG4aKXsdS0OJ2FPTebxqfnd36kKLf9SeE/j/FJmKgRd3AnpfjrHx9qRw9G5FmpWofnlWvQncQa39kwJxpIpOnC7kcjap9jiC2iGAOY/ZaV+HXcb+nxnRc/JVoSZTcMlK4bbArTZ9YXy/cy31UXctMQgSW6zCwSRtqKcynOFwFFameGNMiCpxiSciwHSqnj/Drte5rRTdnLVKUnmWSJBBdu84BJkzPlF62JNojkbploxeVmIJD9AiqYj0WLxoZMoG0Ir/qyeLjqvuuLE+kHmuu0DZwNC/zWUTpRs8AeM54zR7ZULad6t0Qs2E3bE/33wCspuw+ARbkvyTLwDA6TCRetTkdgIudfjVlhEK+6TFWqasgqSg6sO6tBL/4laxd0Q== azureuser@QuickstartAnsible-vm"
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
